# Configuration file for curve generation
# Specify the type of curve generation and input file paths

curve_type: cone # Options: bezier, cone
root_path: /mnt/zhouxinyu/sample_processed
output_path: /mnt/zhouxinyu/field_gen
trunk_size: 60
