# Configuration file for curve generation
# Specify the type of curve generation and input file paths
generate:
  curve_type: bezier # Options: bezier, cone
  output_path: /mnt/zhouxinyu/simsample/chunk_train_3600
  chunk_size: 35  
  beta: 0.003

tasks:
  pick1:
    path: /mnt/public/zhouxinyu/separated/episode0
    max_trajectories: 3600
