# Configuration file for curve generation
# Specify the type of curve generation and input file paths
generate:
  curve_type: bezier # Options: bezier, cone
  output_path: /mnt/yekehe/fieldgen_task_verpick/chunk_train_5400
  chunk_size: 35
  beta: 0.003

tasks:
  pick1:
    path: /mnt/public/yekehe/separated/episode0
    max_trajectories: 5400