# Configuration file for curve generation
# Specify the type of curve generation and input file paths

curve_type: bezier # Options: bezier, cone
root_path: /mnt/yekehe/sample_processed
output_path: /mnt/yekehe/trunk_train_mini
trunk_size: 35
max_trajectories: 1000 # Maximum number of trajectories to process (null for no limit)
