# Configuration file for curve generation
# Specify the type of curve generation and input file paths
generate:
  curve_type: cone # Options: bezier, cone
  output_path: /path/to/output
  chunk_size: 35
  beta: 0.0025
  endpoint_random_radius: 0.1
  multiplier: 10
  reward_target_min: 0.0
  reward_target_max: 1.0

tasks:
  pick0:
    path: /path/to/episode/episode0
    max_trajectories: null
  pick1:
    path: /path/to/episode/episode1
    max_trajectories: null
    
