# Configuration file for curve generation
# Specify the type of curve generation and input file paths

curve_type: cone  # Options: bezier, cone
root_path: /home/agiuser/Application/trans/sample_processed
output_path: ./output/
trunk_size: 32
