# Configuration file for curve generation
# Specify the type of curve generation and input file paths

curve_type: bezier # Options: bezier, cone
root_path: /mnt/yekehe/sample_processed
output_path: /mnt/yekehe/trunk_train
trunk_size: 35
